name:                isocodes
version:             0.1.0.1
github:              "on-ramp/isocodes"
license:             BSD3
author:              "Oleksii Divak"
maintainer:          "oleksii@coinweb.io"
copyright:           "2021 Oleksii Divak"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/on-ramp/isocodes#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- containers
- country
- currency-codes
- http-api-data
- scientific
- text
- unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - ISO.Convert
    - ISO.Country
    - ISO.Country.Codes
    - ISO.Country.Internal
    - ISO.Currency
    - ISO.Currency.Codes
    - ISO.Currency.Internal

tests:
  coherence:
    main: Coherence.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - hspec
      - isocodes
      - QuickCheck
